stages:
  - build
  - deploy

build_images:
  image: docker:cli
  stage: build
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker-compose build
    - docker push registry.gitlab.com/young-epish/mipt_devops/nginx-customized
    - docker push registry.gitlab.com/young-epish/mipt_devops/postgres-customized
  tags:
    - gitlab-org-docker


deploy_compose:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa master.hadoop.akhcheck.ru >> ~/.ssh/known_hosts
    - base64 -d $SSH_KEY_NAME > $SSH_DECODED_KEY
    - chmod 0600 $SSH_DECODED_KEY
    - ssh -i $SSH_DECODED_KEY student07@master.hadoop.akhcheck.ru docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - ssh -i $SSH_DECODED_KEY student07@master.hadoop.akhcheck.ru docker pull registry.gitlab.com/young-epish/mipt_devops/nginx-customized
    - ssh -i $SSH_DECODED_KEY student07@master.hadoop.akhcheck.ru docker pull registry.gitlab.com/young-epish/mipt_devops/postgres-customized
    - scp -i $SSH_DECODED_KEY docker-compose-deploy.yml student07@master.hadoop.akhcheck.ru:~/docker-compose.yml
    - ssh -i $SSH_DECODED_KEY student07@master.hadoop.akhcheck.ru docker compose up -d
