services:
  nginx-customized:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: registry.gitlab.com/young-epish/mipt_devops/nginx-customized
    container_name: nginx-customized
    ports:
      - "35007:35007"

  postgres-customized:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: registry.gitlab.com/young-epish/mipt_devops/postgres-customized
    container_name: postgres-customized
    ports:
      - "45007:45007"